spring.application.name=s0225_01
 
# JPA -----------------------------------------------------------------------------------------------------------
# entity명령어 처리에 대한 내용

# hibernate 설정
spring.jpa.open-in-view=true

# 프로젝트 실행시 자동으로 DDL 생성 : create,update,none – 컬럼생성은 알파벳 순으로 생성됨.
spring.jpa.hibernate.ddl-auto=update

# entity 생성시, DB생성시 변수명 그대로 유 컬럼필드 사용
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# jpa numbering 전략
spring.jpa.hibernate.use-new-id-generator-mappings=false

# JPA 처리시에 발생하는 SQL을 보여줄것인지 결정
spring.jpa.show-sql=true

# JPA 구현체인 Hibernate가 동작하면서 발생하는 SQL을 formating해서 출력
spring.jpa.properties.hibernate.format_sql=true
